export const bookmarkedBids = [
  { id: 1, entityType: "Federal", bidName: "IT Infrastructure Modernization - Department of Defense", openDate: "10th July, 2025", closedDate: "25th July, 2025", countdown: "15 Days" },
  { id: 2, entityType: "State", bidName: "Highway Expansion Project - Texas DOT", openDate: "5th June, 2025", closedDate: "20th June, 2025", countdown: "8 Days" },
  { id: 3, entityType: "County", bidName: "School Meal Supply Contract - Orange County", openDate: "1st August, 2025", closedDate: "12th August, 2025", countdown: "12 Days" },
  { id: 4, entityType: "City", bidName: "Smart Traffic Signal System - City of Chicago", openDate: "15th May, 2025", closedDate: "30th May, 2025", countdown: "5 Days" },
  { id: 5, entityType: "Federal", bidName: "Cybersecurity Services - Homeland Security", openDate: "20th April, 2025", closedDate: "5th May, 2025", countdown: "3 Days" },
  { id: 6, entityType: "Hospital", bidName: "Medical Equipment Supply - Johns Hopkins Hospital", openDate: "7th June, 2025", closedDate: "21st June, 2025", countdown: "9 Days" },
  { id: 7, entityType: "University", bidName: "Laboratory Renovation - MIT", openDate: "1st July, 2025", closedDate: "18th July, 2025", countdown: "13 Days" },
  { id: 8, entityType: "City", bidName: "Waste Management Contract - City of Los Angeles", openDate: "3rd June, 2025", closedDate: "15th June, 2025", countdown: "6 Days" },
  { id: 9, entityType: "County", bidName: "Bridge Repair Project - King County", openDate: "22nd July, 2025", closedDate: "10th August, 2025", countdown: "17 Days" },
  { id: 10, entityType: "State", bidName: "Renewable Energy Procurement - Florida Energy Dept", openDate: "2nd August, 2025", closedDate: "20th August, 2025", countdown: "19 Days" },
  { id: 11, entityType: "Federal", bidName: "Air Traffic Control Systems Upgrade - FAA", openDate: "10th June, 2025", closedDate: "28th June, 2025", countdown: "14 Days" },
  { id: 12, entityType: "City", bidName: "Public Housing Maintenance - City of Detroit", openDate: "12th July, 2025", closedDate: "25th July, 2025", countdown: "11 Days" },
  { id: 13, entityType: "State", bidName: "School Bus Fleet Expansion - New York State", openDate: "14th May, 2025", closedDate: "29th May, 2025", countdown: "7 Days" },
  { id: 14, entityType: "University", bidName: "AI Research Center Setup - Harvard University", openDate: "1st August, 2025", closedDate: "18th August, 2025", countdown: "15 Days" },
  { id: 15, entityType: "County", bidName: "Water Treatment Plant Maintenance - Cook County", openDate: "6th June, 2025", closedDate: "19th June, 2025", countdown: "10 Days" },
  { id: 16, entityType: "Federal", bidName: "Military Vehicles Supply - US Army", openDate: "5th July, 2025", closedDate: "20th July, 2025", countdown: "12 Days" },
  { id: 17, entityType: "City", bidName: "Green Park Development - City of San Francisco", openDate: "10th June, 2025", closedDate: "25th June, 2025", countdown: "9 Days" },
  { id: 18, entityType: "Hospital", bidName: "COVID-19 Vaccine Distribution - Mayo Clinic", openDate: "7th August, 2025", closedDate: "22nd August, 2025", countdown: "16 Days" },
  { id: 19, entityType: "State", bidName: "Renewable Solar Panels - Arizona State", openDate: "3rd July, 2025", closedDate: "15th July, 2025", countdown: "10 Days" },
  { id: 20, entityType: "Federal", bidName: "Satellite Communication Services - NASA", openDate: "1st September, 2025", closedDate: "20th September, 2025", countdown: "25 Days" },
  { id: 21, entityType: "County", bidName: "Library Renovation Project - Dallas County", openDate: "14th June, 2025", closedDate: "30th June, 2025", countdown: "12 Days" },
  { id: 22, entityType: "City", bidName: "Fire Station Construction - City of Houston", openDate: "2nd August, 2025", closedDate: "18th August, 2025", countdown: "13 Days" },
  { id: 23, entityType: "State", bidName: "Wildlife Conservation Program - Colorado", openDate: "10th July, 2025", closedDate: "28th July, 2025", countdown: "15 Days" },
  { id: 24, entityType: "Federal", bidName: "AI-Based Border Security Systems - DHS", openDate: "6th June, 2025", closedDate: "20th June, 2025", countdown: "8 Days" },
  { id: 25, entityType: "University", bidName: "Library Digitalization - Yale University", openDate: "12th August, 2025", closedDate: "30th August, 2025", countdown: "18 Days" },
  { id: 26, entityType: "Federal", bidName: "Healthcare Data Cloud Hosting - HHS", openDate: "4th July, 2025", closedDate: "18th July, 2025", countdown: "11 Days" },
  { id: 27, entityType: "City", bidName: "Smart Parking Meters - City of Miami", openDate: "1st May, 2025", closedDate: "16th May, 2025", countdown: "4 Days" },
  { id: 28, entityType: "County", bidName: "Flood Control System Upgrade - Harris County", openDate: "3rd June, 2025", closedDate: "20th June, 2025", countdown: "9 Days" },
  { id: 29, entityType: "State", bidName: "Statewide Broadband Expansion - Georgia", openDate: "15th July, 2025", closedDate: "5th August, 2025", countdown: "19 Days" },
  { id: 30, entityType: "Hospital", bidName: "Ambulance Fleet Renewal - Cleveland Clinic", openDate: "20th May, 2025", closedDate: "2nd June, 2025", countdown: "6 Days" },
  { id: 31, entityType: "Federal", bidName: "AI Drone Surveillance - Air Force", openDate: "12th July, 2025", closedDate: "30th July, 2025", countdown: "15 Days" },
  { id: 32, entityType: "City", bidName: "Public Library Wi-Fi Upgrade - City of Seattle", openDate: "8th June, 2025", closedDate: "22nd June, 2025", countdown: "10 Days" },
  { id: 33, entityType: "County", bidName: "Bridge Safety Audit - Montgomery County", openDate: "18th July, 2025", closedDate: "3rd August, 2025", countdown: "12 Days" },
  { id: 34, entityType: "State", bidName: "Smart Agriculture Program - Iowa", openDate: "14th August, 2025", closedDate: "28th August, 2025", countdown: "14 Days" },
  { id: 35, entityType: "Federal", bidName: "Maritime Radar System - US Navy", openDate: "22nd June, 2025", closedDate: "8th July, 2025", countdown: "15 Days" },
  { id: 36, entityType: "University", bidName: "Biotechnology Research Lab - UC Berkeley", openDate: "9th May, 2025", closedDate: "25th May, 2025", countdown: "7 Days" },
  { id: 37, entityType: "City", bidName: "Public Transit Expansion - City of Phoenix", openDate: "11th June, 2025", closedDate: "26th June, 2025", countdown: "11 Days" },
  { id: 38, entityType: "County", bidName: "Courthouse Renovation - Maricopa County", openDate: "20th July, 2025", closedDate: "6th August, 2025", countdown: "15 Days" },
  { id: 39, entityType: "Federal", bidName: "AI-Powered Health Records System - VA", openDate: "30th June, 2025", closedDate: "16th July, 2025", countdown: "14 Days" },
  { id: 40, entityType: "State", bidName: "Disaster Recovery Plan - Louisiana", openDate: "5th August, 2025", closedDate: "21st August, 2025", countdown: "16 Days" },
  { id: 41, entityType: "City", bidName: "Water Pipeline Expansion - City of Denver", openDate: "13th June, 2025", closedDate: "28th June, 2025", countdown: "10 Days" },
  { id: 42, entityType: "County", bidName: "Community Park Renovation - Broward County", openDate: "8th July, 2025", closedDate: "23rd July, 2025", countdown: "13 Days" },
  { id: 43, entityType: "Hospital", bidName: "Digital Patient Record System - Mount Sinai", openDate: "1st August, 2025", closedDate: "15th August, 2025", countdown: "12 Days" },
  { id: 44, entityType: "State", bidName: "Electric Bus Fleet - Oregon", openDate: "25th July, 2025", closedDate: "12th August, 2025", countdown: "14 Days" },
  { id: 45, entityType: "Federal", bidName: "AI-Powered Predictive Policing - DOJ", openDate: "6th June, 2025", closedDate: "24th June, 2025", countdown: "12 Days" },
  { id: 46, entityType: "University", bidName: "Renewable Energy Plant - Princeton University", openDate: "17th July, 2025", closedDate: "1st August, 2025", countdown: "12 Days" },
  { id: 47, entityType: "County", bidName: "Storm Drain Upgrade - Palm Beach County", openDate: "9th June, 2025", closedDate: "25th June, 2025", countdown: "11 Days" },
  { id: 48, entityType: "City", bidName: "Public Wi-Fi Expansion - City of Dallas", openDate: "21st July, 2025", closedDate: "6th August, 2025", countdown: "15 Days" },
  { id: 49, entityType: "State", bidName: "AI Traffic Management System - Illinois", openDate: "1st September, 2025", closedDate: "18th September, 2025", countdown: "20 Days" },
  { id: 50, entityType: "Federal", bidName: "Green Energy Research Grants - DOE", openDate: "10th July, 2025", closedDate: "30th July, 2025", countdown: "18 Days" },
];

export const followData = [
  {
    id: 1,
    entityType: "Federal",
    bidName: "Supply of Solar Panels for Federal Buildings",
    openDate: "2025-01-05",
    closedDate: "2025-02-15",
    countdown: "14 days left",
  },
  {
    id: 2,
    entityType: "State",
    bidName: "Road Rehabilitation Project - California DOT",
    openDate: "2025-01-10",
    closedDate: "2025-02-20",
    countdown: "19 days left",
  },
  {
    id: 3,
    entityType: "City",
    bidName: "Smart Traffic Lights Installation - Austin",
    openDate: "2025-01-12",
    closedDate: "2025-02-25",
    countdown: "24 days left",
  },
  {
    id: 4,
    entityType: "County",
    bidName: "County Library Renovation - Orange County",
    openDate: "2025-01-15",
    closedDate: "2025-02-28",
    countdown: "27 days left",
  },
  {
    id: 5,
    entityType: "University",
    bidName: "Cafeteria Services Contract - NYU",
    openDate: "2025-01-18",
    closedDate: "2025-03-01",
    countdown: "28 days left",
  },
  {
    id: 6,
    entityType: "Federal",
    bidName: "Supply of Medical Kits - FEMA",
    openDate: "2025-01-20",
    closedDate: "2025-03-05",
    countdown: "32 days left",
  },
  {
    id: 7,
    entityType: "State",
    bidName: "IT Support Services - Texas Education Department",
    openDate: "2025-01-22",
    closedDate: "2025-03-08",
    countdown: "35 days left",
  },
  {
    id: 8,
    entityType: "City",
    bidName: "City Park Lighting Upgrade - Denver",
    openDate: "2025-01-25",
    closedDate: "2025-03-10",
    countdown: "37 days left",
  },
  {
    id: 9,
    entityType: "County",
    bidName: "Water Treatment Plant Maintenance - Cook County",
    openDate: "2025-01-28",
    closedDate: "2025-03-12",
    countdown: "39 days left",
  },
  {
    id: 10,
    entityType: "University",
    bidName: "Sports Complex Construction - UCLA",
    openDate: "2025-01-30",
    closedDate: "2025-03-15",
    countdown: "42 days left",
  },
  {
    id: 11,
    entityType: "Federal",
    bidName: "Drone Surveillance Equipment - Department of Defense",
    openDate: "2025-02-01",
    closedDate: "2025-03-20",
    countdown: "47 days left",
  },
  {
    id: 12,
    entityType: "State",
    bidName: "Highway Expansion - Florida DOT",
    openDate: "2025-02-02",
    closedDate: "2025-03-22",
    countdown: "49 days left",
  },
  {
    id: 13,
    entityType: "City",
    bidName: "Public Wi-Fi Expansion - San Francisco",
    openDate: "2025-02-03",
    closedDate: "2025-03-25",
    countdown: "52 days left",
  },
  {
    id: 14,
    entityType: "County",
    bidName: "New Jail Facility Construction - Harris County",
    openDate: "2025-02-04",
    closedDate: "2025-03-28",
    countdown: "55 days left",
  },
  {
    id: 15,
    entityType: "University",
    bidName: "Library Digitalization Project - Harvard",
    openDate: "2025-02-05",
    closedDate: "2025-03-30",
    countdown: "57 days left",
  },
  {
    id: 16,
    entityType: "Federal",
    bidName: "Cybersecurity Services - Homeland Security",
    openDate: "2025-02-06",
    closedDate: "2025-04-01",
    countdown: "59 days left",
  },
  {
    id: 17,
    entityType: "State",
    bidName: "Renewable Energy Grid Upgrade - New York",
    openDate: "2025-02-07",
    closedDate: "2025-04-03",
    countdown: "61 days left",
  },
  {
    id: 18,
    entityType: "City",
    bidName: "Waste Management Contract - Los Angeles",
    openDate: "2025-02-08",
    closedDate: "2025-04-05",
    countdown: "63 days left",
  },
  {
    id: 19,
    entityType: "County",
    bidName: "Emergency Response Vehicles - Miami-Dade",
    openDate: "2025-02-09",
    closedDate: "2025-04-07",
    countdown: "65 days left",
  },
  {
    id: 20,
    entityType: "University",
    bidName: "Campus Wi-Fi Upgrade - MIT",
    openDate: "2025-02-10",
    closedDate: "2025-04-09",
    countdown: "67 days left",
  },
  {
    id: 21,
    entityType: "Federal",
    bidName: "Satellite Launch Services - NASA",
    openDate: "2025-02-12",
    closedDate: "2025-04-12",
    countdown: "70 days left",
  },
  {
    id: 22,
    entityType: "State",
    bidName: "School Bus Fleet Renewal - Georgia",
    openDate: "2025-02-14",
    closedDate: "2025-04-14",
    countdown: "72 days left",
  },
  {
    id: 23,
    entityType: "City",
    bidName: "Fire Station Construction - Seattle",
    openDate: "2025-02-15",
    closedDate: "2025-04-16",
    countdown: "74 days left",
  },
  {
    id: 24,
    entityType: "County",
    bidName: "Healthcare Center Expansion - Maricopa",
    openDate: "2025-02-16",
    closedDate: "2025-04-18",
    countdown: "76 days left",
  },
  {
    id: 25,
    entityType: "University",
    bidName: "Student Housing Development - Stanford",
    openDate: "2025-02-17",
    closedDate: "2025-04-20",
    countdown: "78 days left",
  },
  {
    id: 26,
    entityType: "Federal",
    bidName: "Border Security Equipment - Customs & Border Protection",
    openDate: "2025-02-18",
    closedDate: "2025-04-22",
    countdown: "80 days left",
  },
  {
    id: 27,
    entityType: "State",
    bidName: "Flood Control Project - Louisiana",
    openDate: "2025-02-19",
    closedDate: "2025-04-24",
    countdown: "82 days left",
  },
  {
    id: 28,
    entityType: "City",
    bidName: "Public Transport Expansion - Chicago",
    openDate: "2025-02-20",
    closedDate: "2025-04-26",
    countdown: "84 days left",
  },
  {
    id: 29,
    entityType: "County",
    bidName: "Bridge Repair Project - King County",
    openDate: "2025-02-21",
    closedDate: "2025-04-28",
    countdown: "86 days left",
  },
  {
    id: 30,
    entityType: "University",
    bidName: "AI Research Lab Construction - Carnegie Mellon",
    openDate: "2025-02-22",
    closedDate: "2025-04-30",
    countdown: "88 days left",
  },
  {
    id: 31,
    entityType: "Federal",
    bidName: "Navy Ship Maintenance Contract",
    openDate: "2025-02-23",
    closedDate: "2025-05-02",
    countdown: "90 days left",
  },
  {
    id: 32,
    entityType: "State",
    bidName: "Renewable Energy Study - Oregon",
    openDate: "2025-02-24",
    closedDate: "2025-05-04",
    countdown: "92 days left",
  },
  {
    id: 33,
    entityType: "City",
    bidName: "Community Center Construction - Phoenix",
    openDate: "2025-02-25",
    closedDate: "2025-05-06",
    countdown: "94 days left",
  },
  {
    id: 34,
    entityType: "County",
    bidName: "Public Safety Equipment - Clark County",
    openDate: "2025-02-26",
    closedDate: "2025-05-08",
    countdown: "96 days left",
  },
  {
    id: 35,
    entityType: "University",
    bidName: "Medical Research Equipment - Johns Hopkins",
    openDate: "2025-02-27",
    closedDate: "2025-05-10",
    countdown: "98 days left",
  },
  {
    id: 36,
    entityType: "Federal",
    bidName: "Cloud Infrastructure Services - GSA",
    openDate: "2025-02-28",
    closedDate: "2025-05-12",
    countdown: "100 days left",
  },
  {
    id: 37,
    entityType: "State",
    bidName: "Bridge Construction - Massachusetts",
    openDate: "2025-03-01",
    closedDate: "2025-05-14",
    countdown: "102 days left",
  },
  {
    id: 38,
    entityType: "City",
    bidName: "City Hall Renovation - Houston",
    openDate: "2025-03-02",
    closedDate: "2025-05-16",
    countdown: "104 days left",
  },
  {
    id: 39,
    entityType: "County",
    bidName: "Emergency Shelter Expansion - Alameda",
    openDate: "2025-03-03",
    closedDate: "2025-05-18",
    countdown: "106 days left",
  },
  {
    id: 40,
    entityType: "University",
    bidName: "Green Campus Initiative - Princeton",
    openDate: "2025-03-04",
    closedDate: "2025-05-20",
    countdown: "108 days left",
  },
  {
    id: 41,
    entityType: "Federal",
    bidName: "Defense Communications Upgrade - Pentagon",
    openDate: "2025-03-05",
    closedDate: "2025-05-22",
    countdown: "110 days left",
  },
  {
    id: 42,
    entityType: "State",
    bidName: "Rural Internet Expansion - Kansas",
    openDate: "2025-03-06",
    closedDate: "2025-05-24",
    countdown: "112 days left",
  },
  {
    id: 43,
    entityType: "City",
    bidName: "Sewage Treatment Plant Upgrade - Detroit",
    openDate: "2025-03-07",
    closedDate: "2025-05-26",
    countdown: "114 days left",
  },
  {
    id: 44,
    entityType: "County",
    bidName: "School Construction - Broward County",
    openDate: "2025-03-08",
    closedDate: "2025-05-28",
    countdown: "116 days left",
  },
  {
    id: 45,
    entityType: "University",
    bidName: "Engineering Building Expansion - Purdue",
    openDate: "2025-03-09",
    closedDate: "2025-05-30",
    countdown: "118 days left",
  },
  {
    id: 46,
    entityType: "Federal",
    bidName: "Air Traffic Control Systems - FAA",
    openDate: "2025-03-10",
    closedDate: "2025-06-01",
    countdown: "120 days left",
  },
  {
    id: 47,
    entityType: "State",
    bidName: "Public Health Outreach Program - Illinois",
    openDate: "2025-03-11",
    closedDate: "2025-06-03",
    countdown: "122 days left",
  },
  {
    id: 48,
    entityType: "City",
    bidName: "Downtown Revitalization - Boston",
    openDate: "2025-03-12",
    closedDate: "2025-06-05",
    countdown: "124 days left",
  },
  {
    id: 49,
    entityType: "County",
    bidName: "Flood Prevention Infrastructure - Jefferson",
    openDate: "2025-03-13",
    closedDate: "2025-06-07",
    countdown: "126 days left",
  },
  {
    id: 50,
    entityType: "University",
    bidName: "AI & Robotics Lab - Georgia Tech",
    openDate: "2025-03-14",
    closedDate: "2025-06-09",
    countdown: "128 days left",
  },
];
